AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito Users Pool Authentication + API with protected routes
Parameters:
  CognitoUserPoolName:
    Type: String
    Default: UsersManagementUserPool
  CognitoUserPoolClientName:
    Type: String
    Default: UsersManagementPoolClient
  UserpoolDomainPrefix:
    Type: String
    Default: franrobles8-users-management-1
Resources:
  UsersManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors: '''*'''
      Auth:
        DefaultAuthorizer: UsersManagementAuthorizer
        Authorizers:
          UsersManagementAuthorizer:
            UserPoolArn:
              Fn::GetAtt:
              - UsersManagementUserPool
              - Arn
  UsersManagementLambdaAuth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://users-management-bucket/9974ae0a1350d2baa61a4b9dcfe50db5
      Handler: index.usersHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          COGNITO_USER_POOL_CLIENT_ID:
            Ref: UsersManagementCognitoUserPoolClient
          COGNITO_USER_POOL_ID:
            Ref: UsersManagementUserPool
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId:
              Ref: UsersManagementApi
            Path: /auth/register
            Method: POST
            Auth:
              Authorizer: NONE
        LoginUser:
          Type: Api
          Properties:
            RestApiId:
              Ref: UsersManagementApi
            Path: /auth/login
            Method: POST
            Auth:
              Authorizer: NONE
  UsersManagementUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Ref: CognitoUserPoolName
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailSubject: Activation link
        EmailSubjectByLink: Click on the link to activate your acount
      Policies:
        PasswordPolicy:
          TemporaryPasswordValidityDays: 1
          MinimumLength: 6
          RequireNumbers: true
      UsernameAttributes:
      - email
      AutoVerifiedAttributes:
      - email
      Schema:
      - AttributeDataType: String
        Name: email
        Required: true
      - AttributeDataType: String
        Name: firstname
        Required: false
      - AttributeDataType: String
        Name: lastname
        Required: false
  UsersManagementCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: UsersManagementUserPool
      ClientName:
        Ref: CognitoUserPoolClientName
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 20
      ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain:
        Fn::Sub: ${UserpoolDomainPrefix}
      UserPoolId:
        Ref: UsersManagementUserPool
Outputs:
  Region:
    Description: Region
    Value:
      Ref: AWS::Region
  ApiUrl:
    Description: API Endpoint for dev environment
    Value:
      Fn::Sub: https://${UsersManagementApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/
