AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Complete MiniApp to test the capabilities of AWS Serverless services
Resources:
  UsersManagementResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.eu-west-2.amazonaws.com/complete-mini-app-bucket/13e8e3999edfdb689a128b27d7ed0b37.template
  DatabaseResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.eu-west-2.amazonaws.com/complete-mini-app-bucket/d9cf21b114dd5ca24494cd01efcde258.template
  PdfQueueResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.eu-west-2.amazonaws.com/complete-mini-app-bucket/47e9b2d098f3f41cd6ed89fe69ba9cff.template
      Parameters:
        pdfBucketName: complete-miniapp-pdf-bucket
